<a href="https://colab.research.google.com/github/ShaheerBaba/ML_PROJECTS/blob/main/Titanic_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Survival Prediction Project

This notebook demonstrates a complete machine learning workflow to predict passenger survival on the Titanic, including data loading, preprocessing, model training, and evaluation using various classification algorithms.

In [152]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## 1. Data Loading and Initial Exploration

In this section, we load the Titanic dataset and perform an initial exploration to understand its structure, identify missing values, and check for duplicates.

In [153]:
df = sns.load_dataset("titanic")

In [154]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## 2. Data Preprocessing

This section focuses on cleaning and transforming the data to prepare it for machine learning models. This involves handling missing values, dropping irrelevant columns, and encoding categorical features.

In [155]:
df.duplicated().sum()

np.int64(107)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [157]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [158]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [159]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [160]:
df.drop(columns=['deck','embark_town','adult_male','class','who','alive'],axis=1,inplace=True)

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [162]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [163]:
df['age'].fillna(df['age'].mean(),inplace=True)

/tmp/ipykernel_1588/1492264711.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [165]:
df.dropna(subset=['embarked'],inplace=True)

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [167]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [168]:
df['sex'] = le.fit_transform(df['sex'])

In [169]:
df['embarked'] = le.fit_transform(df['embarked'])

In [170]:
df = df.astype(int)

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    int64
 3   age       889 non-null    int64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    int64
 7   embarked  889 non-null    int64
 8   alone     889 non-null    int64
dtypes: int64(9)
memory usage: 69.5 KB

In [172]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

## 3. Data Splitting and Scaling

Here, we split the dataset into training and testing sets, and then scale the numerical features to ensure that all features contribute equally to the model training process.

In [173]:
x = df.drop('survived',axis=1)

In [174]:
y = df["survived"]

In [175]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [176]:
from sklearn.preprocessing import StandardScaler

In [177]:
scaler = StandardScaler()

In [178]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [179]:
from sklearn.linear_model import LogisticRegression

In [216]:
from sklearn.linear_model import LogisticRegression
# Initialize the Logistic Regression model
# random_state ensures reproducibility of results
# max_iter is increased to ensure the optimization algorithm converges
model = LogisticRegression(random_state=42, max_iter=200)

In [181]:
# Train the Logistic Regression model using the scaled training data
# The model learns the relationship between features (x_train_scaled) and the target (y_train)
model.fit(x_train_scaled,y_train)

LogisticRegression(max_iter=200, random_state=42)

In [182]:
# Make predictions on the scaled test data using the trained Logistic Regression model
y_pred = model.predict(x_test_scaled)

In [183]:
# Display the predictions made by the Logistic Regression model for the test set
# These are the predicted 'survived' (0 or 1) values
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

### 4.1 Logistic Regression

First, we train a Logistic Regression model, a simple yet effective linear classifier.

In [217]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and testing data
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test) # Use transform for test set to prevent data leakage

## 4. Model Training and Evaluation

In this section, we train and evaluate several classification models on the preprocessed data. We will compare their performance using accuracy, confusion matrix, and classification reports.

In [185]:
from sklearn.neighbors import KNeighborsClassifier

In [218]:
from sklearn.neighbors import KNeighborsClassifier
# Initialize the K-Nearest Neighbors model with 5 neighbors
# 'n_neighbors' specifies the number of neighbors to consider for classification
knn_model = KNeighborsClassifier(n_neighbors=5)

In [187]:
# Train the KNN model using the scaled training data
# The model 'learns' by storing the training data points
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [188]:
# Make predictions on the scaled test data using the trained KNN model
y_pred_knn = knn_model.predict(x_test_scaled)

In [189]:
# Display the predictions made by the KNN model for the test set
# These are the predicted 'survived' (0 or 1) values from the KNN model
y_pred_knn

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [190]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [191]:
print("Accuracy score :",accuracy_score(y_test,y_pred_knn))

Accuracy score : 0.7921348314606742

In [192]:
print("confusion matrix :",confusion_matrix(y_test,y_pred_knn))

confusion matrix : [[89 20]
 [17 52]]

In [193]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178

### 4.2 K-Nearest Neighbors (KNN)

Next, we train a K-Nearest Neighbors classifier, a non-parametric method used for classification and regression.

In [194]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

# Initialize the Gaussian Naive Bayes model
model_NB = GaussianNB()

In [195]:
# Train the Naive Bayes model using the original (unscaled) training data
# Gaussian Naive Bayes makes assumptions about feature distributions but typically doesn't require scaling.
model_NB.fit(x_train,y_train)

GaussianNB()

In [196]:
# Make predictions on the original (unscaled) test data using the trained Naive Bayes model
y_pred_NB = model_NB.predict(x_test)

In [197]:
# Display the predictions made by the Naive Bayes model for the test set
# These are the predicted 'survived' (0 or 1) values from the Naive Bayes model
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [198]:
print(accuracy_score(y_test,y_pred_NB))
print(confusion_matrix(y_test,y_pred_NB))
print(classification_report(y_test,y_pred_NB))

0.7752808988764045
[[84 25]
 [15 54]]
              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

### 4.3 Gaussian Naive Bayes

Then, we use a Gaussian Naive Bayes classifier, which assumes features are normally distributed.

In [199]:
# Import DecisionTreeClassifier model
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree model with a random state for reproducibility
# random_state ensures that the splits in the tree are consistent across runs
model_DT = DecisionTreeClassifier(random_state=42)

In [200]:
# Train the Decision Tree model using the scaled training data
# Decision Trees can handle unscaled data, but scaling can sometimes stabilize performance
model_DT.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [201]:
# Make predictions on the scaled test data using the trained Decision Tree model
y_pred_DT = model_DT.predict(x_test_scaled)

In [202]:
# Display the predictions made by the Decision Tree model for the test set
# These are the predicted 'survived' (0 or 1) values from the Decision Tree model
y_pred_DT

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0])

In [203]:
print(accuracy_score(y_test,y_pred_DT))
print(confusion_matrix(y_test,y_pred_DT))
print(classification_report(y_test,y_pred_DT))

0.8033707865168539
[[90 19]
 [16 53]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

### 4.4 Decision Tree Classifier

We also train a Decision Tree, a non-linear model that partitions the data based on feature values.

In [204]:
from sklearn.svm import SVC

In [219]:
from sklearn.svm import SVC
# Initialize the Support Vector Machine (SVM) model with a radial basis function (rbf) kernel
# The 'rbf' kernel is good for non-linear decision boundaries.
# random_state ensures reproducibility.
model_SVM = SVC(kernel = "rbf", random_state=42)

In [206]:
# Train the SVM model using the scaled training data
# SVMs are sensitive to feature scaling, so using scaled data is crucial for optimal performance.
model_SVM.fit(x_train_scaled,y_train)

SVC(random_state=42)

In [207]:
# Make predictions on the scaled test data using the trained SVM model
y_pred_SVM = model_SVM.predict(x_test_scaled)

In [208]:
# Display the predictions made by the SVM model for the test set
# These are the predicted 'survived' (0 or 1) values from the SVM model
y_pred_SVM

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [209]:
print(accuracy_score(y_test,y_pred_SVM))
print(confusion_matrix(y_test,y_pred_SVM))
print(classification_report(y_test,y_pred_SVM))

0.8146067415730337
[[91 18]
 [15 54]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178

### 4.5 Support Vector Machine (SVM)

Finally, we train a Support Vector Machine with a radial basis function (RBF) kernel, a powerful model for complex classification tasks.

In [210]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [211]:
x=df.drop("survived",axis=1)
y = df['survived']

In [212]:
x_scaled = scaler.fit_transform(x)

In [213]:
# Import cross_val_score for evaluating model performance using cross-validation
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation on the SVM model using the scaled data
# 'cv=5' means the data is split into 5 folds, and the model is trained/tested 5 times.
# 'scoring='accuracy'' specifies that accuracy is the metric to evaluate.
scores = cross_val_score(model_SVM,x_scaled,y,cv = 5,scoring='accuracy')

In [214]:
# Display the accuracy scores from each fold of the cross-validation
# This array shows the accuracy obtained in each of the 5 folds.
scores

array([0.83146067, 0.82022472, 0.81460674, 0.80898876, 0.86440678])

In [215]:
# Calculate and display the mean accuracy across all cross-validation folds
# This gives a more robust estimate of the model's performance than a single train-test split.
acc = scores.mean()
acc

np.float64(0.8279375357074844)

## 5. Conclusion

This project demonstrated various machine learning techniques for binary classification on the Titanic dataset, from data preprocessing to model evaluation. The SVM model showed the highest accuracy in this particular setup. Further improvements could involve more sophisticated feature engineering, hyperparameter tuning, and ensemble methods.